manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: custom
      url-base: https://github.com/GoshoPas  # or your GitHub org

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-config-pegasus
      remote: custom
      revision: main  # or a tag/commit/branch

  self:
    path: config
